name: Docker Image CI

on:
  # 开启手动触发
  workflow_dispatch:
    # 允许手动选择一个 tag 版本
    inputs:
      tag:
        description: '输入要构建的版本标签 (例如: v1.0.0)'
        required: true
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
